### ISSUE TITLE
System Error - MSVCP140D.dll

### ISSUE THREAD

**Issue by LoserForever88** [TheBrugne/BC4_Patcher#1]
Running the patcher returns the following error:-

"The code execution cannot proceed because MSVCP140D.dll was not found.  Reinstalling the program may fix the problem."

How to resolve it?

**Comment by TheBrugne** [comment]
Hello,
please let me know if this trick work:
go to this link:
https://learn.microsoft.com/it-it/cpp/windows/latest-supported-vc-redist?view=msvc-170

and download and install the package
https://aka.ms/vs/17/release/vc_redist.x64.exe

You are missing some native dll that should come with windows 10-11
installation

Il giorno dom 7 mag 2023 alle ore 01:53 LoserForever88 <
***@***.***> ha scritto:

**Comment by LoserForever88** [comment]
> Hello, please let me know if this trick work: go to this link: https://learn.microsoft.com/it-it/cpp/windows/latest-supported-vc-redist?view=msvc-170 and download and install the package https://aka.ms/vs/17/release/vc_redist.x64.exe You are missing some native dll that should come with windows 10-11 installation

Thank you for the reply.

Unfortunately this doesn't work.  The error still persists after installing it (https://aka.ms/vs/17/release/vc_redist.x64.exe).  I did restart the PC after the installation.

**Comment by TheBrugne** [comment]
Very strange, you seems to have your windows corrupted (c++ native
libraries are missing)

I just committed another version of the patcher builded in release mode,
this should not require msvcp100 DLL.
Let me know if it works otherwise I'll give you the link to the DLL


Il lun 8 mag 2023, 05:31 LoserForever88 ***@***.***> ha
scritto:

**Comment by LoserForever88** [comment]
> Very strange, you seems to have your windows corrupted (c++ native libraries are missing) I just committed another version of the patcher builded in release mode, this should not require msvcp100 DLL. Let me know if it works otherwise I'll give you the link to the DLL Il lun 8 mag 2023, 05:31 

Thank you.  It works like a charm now.  Thank you so much for all the work and effort :)

**Comment by TheBrugne** [comment]
Thank you for the feedback!

Il mer 10 mag 2023, 13:42 LoserForever88 ***@***.***> ha
scritto:
