### ISSUE TITLE
This license code has been revoked

### ISSUE THREAD

**Issue by LoserForever88** [TheBrugne/BC4_Patcher#2]
Yesterday everything works just fine.  Today this message popped up when I launched the installed program (no update, version 4.4.6.27483).  The whole app terminated after dismissing this message.

**Comment by LoserForever88** [comment]
So 3 days later my portable version is not working either now.  I guess someone from BCompare is monitoring this github.  For now I turn to another privated version. Fuck you Scooter Software.  You still wont get a single buck from us.

**Comment by TheBrugne** [comment]
Hi man, for me my patch still works.
Try to delete any cache in c user appdata local

License check is not online mode, so no way they could block you. The only
way for them to block the key we are using is by updating BC to another
version.

Il giorno dom 18 giu 2023 alle ore 03:44 LoserForever88 <
***@***.***> ha scritto:
